export {
  ResourceDetailActionRow,
  ResourceDetailCollection,
  ResourceDetailList,
  ResourceDetailListItem,
  ResourceDetailPanel,
  type ResourceDetailSurface,
  ResourceDetailStack,
  ResourceOverview,
  ResourcePromptEditor,
  type ResourcePromptContextItem,
  ResourcePromptPreview,
  ResourceProperty,
  ResourcePropertyList,
  ResourceSection,
  ResourceSectionTitle,
} from "./resource/detail-shell";
export {
  ResourceActivitySection,
  ResourceDefinitionSection,
  ResourceDetailConfigurationSection,
  ResourceDetailIncludesSection,
  ResourceDetailOverviewSection,
  ResourceDetailPage,
  ResourceDetailReleaseSection,
  ResourceDetailSection,
  type ResourceDetailSectionKind,
  type ResourceDetailSectionProps,
} from "./resource/detail-sections";
