export type { EmptyInput, Endpoint, Untyped } from "./common.js";
export { typedRoutes } from "@bb/hono-typed-routes";

export {
  createHostDaemonLocalClient,
  openRequestSchema,
  pickFolderResponseSchema,
  restartRequestSchema,
  statusResponseSchema,
} from "./local.js";
export type {
  HostDaemonLocalRoutes,
  HostDaemonLocalSchema,
  OpenRequest,
  PickFolderResponse,
  RestartRequest,
  StatusResponse,
} from "./local.js";

export {
  HOST_DAEMON_COMMAND_TYPES,
  HOST_DAEMON_PROTOCOL_VERSION,
  environmentDestroyCommandSchema,
  environmentProvisionCommandSchema,
  hostDaemonCommandEnvelopeSchema,
  hostDaemonCommandResultReportSchema,
  hostDaemonCommandResultSchemaByType,
  hostDaemonCommandSchema,
  hostDaemonCommandTypeSchema,
  hostDaemonExecutionOptionsSchema,
  hostListFilesCommandSchema,
  hostReadFileCommandSchema,
  providerListCommandSchema,
  providerListModelsCommandSchema,
  threadRenameCommandSchema,
  threadStartCommandSchema,
  threadStopCommandSchema,
  turnRunCommandSchema,
  turnSteerCommandSchema,
  workspaceCommitCommandSchema,
  workspaceDiffCommandSchema,
  workspaceDemoteCommandSchema,
  workspacePromoteCommandSchema,
  workspaceListBranchesCommandSchema,
  workspaceListFilesCommandSchema,
  workspaceSquashMergeCommandSchema,
  workspaceContextSchema,
  workspaceStatusCommandSchema,
} from "./commands.js";
export type {
  HostDaemonCommand,
  HostDaemonCommandEnvelope,
  HostDaemonCommandResult,
  HostDaemonCommandResultByType,
  HostDaemonCommandResultReport,
  HostDaemonCommandType,
  HostDaemonExecutionOptions,
  WorkspaceContext,
} from "./commands.js";

export {
  createHostDaemonClient,
  hostDaemonActiveThreadSchema,
  hostDaemonCommandBatchSchema,
  hostDaemonCommandsQuerySchema,
  hostDaemonDaemonWsMessageSchema,
  hostDaemonEnvironmentChangeRequestSchema,
  hostDaemonEnvironmentChangeSchema,
  hostDaemonEventBatchRequestSchema,
  hostDaemonEventBatchResponseSchema,
  hostDaemonEventEnvelopeSchema,
  hostDaemonServerWsMessageSchema,
  hostDaemonSessionOpenRequestSchema,
  hostDaemonSessionOpenResponseSchema,
  hostDaemonToolCallRequestSchema,
  hostDaemonToolCallResponseSchema,
} from "./session.js";
export type {
  HostDaemonActiveThread,
  HostDaemonCommandBatch,
  HostDaemonCommandsQuery,
  HostDaemonDaemonWsMessage,
  HostDaemonEnvironmentChange,
  HostDaemonEnvironmentChangeRequest,
  HostDaemonEventBatchRequest,
  HostDaemonEventBatchResponse,
  HostDaemonEventEnvelope,
  HostDaemonInternalRoutes,
  HostDaemonInternalSchema,
  HostDaemonServerWsMessage,
  HostDaemonSessionOpenRequest,
  HostDaemonSessionOpenResponse,
  HostDaemonToolCallRequest,
  HostDaemonToolCallResponse,
} from "./session.js";
