export type { EmptyInput, Endpoint, Untyped } from "./common.js";
export { typedRoutes } from "@bb/hono-typed-routes";
export {
  HOST_AUTH_FILE_NAME,
  HOST_ID_FILE_NAME,
  HOST_RUNTIME_MATERIAL_FILE_NAME,
  hostAuthStateSchema,
  hostRuntimeMaterialEnvSchema,
  hostRuntimeMaterialManagedFileSchema,
  hostRuntimeMaterialSnapshotSchema,
  normalizeServerUrl,
} from "./local-state.js";
export type {
  HostAuthState,
  HostRuntimeMaterialManagedFile,
  HostRuntimeMaterialSnapshot,
} from "./local-state.js";

export {
  createHostDaemonLocalClient,
  DEFAULT_EPHEMERAL_HOST_DAEMON_LOCAL_BIND_HOST,
  DEFAULT_EPHEMERAL_HOST_DAEMON_LOCAL_HEALTH_VALUE,
  DEFAULT_EPHEMERAL_HOST_DAEMON_LOCAL_PORT,
  DEFAULT_HOST_DAEMON_LOCAL_HEALTH_PATH,
  DEFAULT_HOST_DAEMON_LOCAL_HEALTH_VALUE,
  healthResponseSchema,
  hostPlatformSchema,
  openWorkspaceRequestSchema,
  openRequestSchema,
  PATHS_EXIST_MAX_PATHS,
  pathsExistRequestSchema,
  pathsExistResponseSchema,
  pickFolderResponseSchema,
  restartRequestSchema,
  statusResponseSchema,
  workspaceOpenTargetIdSchema,
  workspaceOpenTargetIdValues,
  workspaceOpenTargetSchema,
  workspaceOpenTargetsResponseSchema,
} from "./local.js";
export type {
  HealthResponse,
  HostDaemonLocalRoutes,
  HostDaemonLocalSchema,
  HostPlatform,
  OpenWorkspaceRequest,
  OpenRequest,
  PathsExistRequest,
  PathsExistResponse,
  PickFolderResponse,
  RestartRequest,
  StatusResponse,
  WorkspaceOpenTarget,
  WorkspaceOpenTargetId,
  WorkspaceOpenTargetsResponse,
} from "./local.js";

export {
  HOST_DAEMON_COMMAND_TYPES,
  HOST_DAEMON_PROTOCOL_VERSION,
  environmentDestroyCommandSchema,
  environmentProvisionCommandSchema,
  hostSyncRuntimeMaterialCommandSchema,
  hostDaemonCommandEnvelopeSchema,
  hostDaemonCommandResultReportSchema,
  hostDaemonCommandResultSchemaByType,
  hostDaemonCommandSchema,
  hostDaemonCommandTypeSchema,
  hostDaemonExecutionOptionsSchema,
  hostListFilesCommandSchema,
  hostReadFileCommandSchema,
  providerListCommandSchema,
  providerListModelsCommandSchema,
  threadRenameCommandSchema,
  threadStartCommandSchema,
  threadStopCommandSchema,
  turnRunCommandSchema,
  turnSteerCommandSchema,
  workspaceCommitCommandSchema,
  workspaceDiffCommandSchema,
  workspaceDemoteCommandSchema,
  workspacePromoteCommandSchema,
  workspaceListBranchesCommandSchema,
  workspaceListFilesCommandSchema,
  workspaceSquashMergeCommandSchema,
  workspaceContextSchema,
  workspaceStatusCommandSchema,
} from "./commands.js";
export type {
  HostDaemonCommand,
  HostDaemonCommandEnvelope,
  HostDaemonCommandResult,
  HostDaemonCommandResultByType,
  HostDaemonCommandResultReport,
  HostDaemonCommandType,
  HostDaemonExecutionOptions,
  WorkspaceContext,
} from "./commands.js";

export {
  buildHostDaemonWebSocketAuthorizationHeader,
  buildHostDaemonWebSocketProtocols,
  createHostDaemonClient,
  hasHostDaemonWebSocketProtocol,
  hostDaemonEnrollRequestSchema,
  hostDaemonEnrollResponseSchema,
  hostDaemonActiveThreadSchema,
  hostDaemonCommandBatchSchema,
  hostDaemonCommandsQuerySchema,
  hostDaemonDaemonWsMessageSchema,
  hostDaemonEnvironmentChangePayloadSchema,
  hostDaemonEnvironmentChangeRequestSchema,
  hostDaemonEnvironmentChangeSchema,
  hostDaemonEventBatchRequestSchema,
  hostDaemonEventBatchResponseSchema,
  hostDaemonEventEnvelopeSchema,
  hostDaemonRuntimeMaterialQuerySchema,
  hostDaemonServerWsMessageSchema,
  hostDaemonSessionOpenRequestSchema,
  hostDaemonSessionOpenResponseSchema,
  hostDaemonTrackedThreadTargetSchema,
  hostDaemonToolCallRequestSchema,
  hostDaemonToolCallResponseSchema,
  HOST_DAEMON_WEBSOCKET_PROTOCOL,
} from "./session.js";
export type {
  HostDaemonActiveThread,
  HostDaemonCommandBatch,
  HostDaemonEnrollRequest,
  HostDaemonEnrollResponse,
  HostDaemonCommandsQuery,
  HostDaemonDaemonWsMessage,
  HostDaemonEnvironmentChange,
  HostDaemonEnvironmentChangePayload,
  HostDaemonEnvironmentChangeRequest,
  HostDaemonEventBatchRequest,
  HostDaemonEventBatchResponse,
  HostDaemonEventEnvelope,
  HostDaemonInternalRoutes,
  HostDaemonInternalSchema,
  HostDaemonRuntimeMaterialQuery,
  HostDaemonServerWsMessage,
  HostDaemonSessionOpenRequest,
  HostDaemonSessionOpenResponse,
  HostDaemonTrackedThreadTarget,
  HostDaemonToolCallRequest,
  HostDaemonToolCallResponse,
} from "./session.js";
