export const SAMPLE_LIST = [
  "Available models",
  "",
  "auto - Auto",
  "gpt-5.3-codex-low - Codex 5.3 Low",
  "gpt-5.3-codex-low-fast - Codex 5.3 Low Fast",
  "gpt-5.3-codex - Codex 5.3",
  "gpt-5.3-codex-fast - Codex 5.3 Fast",
  "gpt-5.3-codex-high - Codex 5.3 High",
  "gpt-5.3-codex-xhigh - Codex 5.3 Extra High",
  "gpt-5.1-codex-max-low - Codex 5.1 Max Low",
  "gpt-5.1-codex-max-medium - Codex 5.1 Max",
  "gpt-5.1-codex-max-high - Codex 5.1 Max High",
  "gpt-5.5-low - GPT-5.5 1M Low",
  "gpt-5.5-medium - GPT-5.5 1M",
  "gpt-5.5-extra-high - GPT-5.5 1M Extra High",
  "gpt-5.5-none - GPT-5.5 1M None",
  "claude-4.6-opus-high - Opus 4.6 1M",
  "claude-4.6-opus-max - Opus 4.6 1M Max",
  "claude-4.6-opus-high-thinking - Opus 4.6 1M Thinking",
  "Tip: use --model <id> to switch.",
].join("\n");
