export type {
  EmptyInput,
  Endpoint,
  PathId,
  PathProjectAutomationId,
  PathProjectId,
  PathThreadAndDraft,
  Untyped,
} from "./common.js";

export { apiErrorSchema, domainErrorCodeSchema } from "./errors.js";
export type { ApiError, DomainErrorCode } from "./errors.js";

export {
  AUTOMATION_NAME_MAX_LENGTH,
  archiveThreadRequestSchema,
  automationActionSchema,
  automationNameSchema,
  automationScheduleTriggerSchema,
  automationSchema,
  automationValidationIssueSchema,
  automationValidationSchema,
  commitActionResponseSchema,
  createAutomationRequestSchema,
  createHostJoinRequestSchema,
  createHostJoinResponseSchema,
  createDraftRequestSchema,
  createManagerThreadRequestSchema,
  createProjectRequestSchema,
  createProjectSourceRequestSchema,
  createThreadRequestSchema,
  environmentArgsSchema,
  environmentActionApiErrorSchema,
  environmentActionFailureDetailsSchema,
  environmentActionRequestSchema,
  environmentActionResponseSchema,
  environmentDiffQuerySchema,
  environmentStatusQuerySchema,
  environmentActionTypeSchema,
  environmentStatusResponseSchema,
  threadStorageContentQuerySchema,
  threadStorageFilesQuerySchema,
  projectAttachmentContentQuerySchema,
  projectFilesQuerySchema,
  projectResponseSchema,
  sendDraftRequestSchema,
  sendDraftResponseSchema,
  sendMessageModeSchema,
  sendMessageRequestSchema,
  scheduledThreadAutomationActionSchema,
  squashMergeActionResponseSchema,
  squashMergeOptionsSchema,
  systemConfigResponseSchema,
  systemSandboxBackendsResponseSchema,
  systemSandboxBackendInfoSchema,
  systemProviderInfoSchema,
  threadContextWindowUsageSchema,
  threadDraftListResponseSchema,
  threadEventWaitQuerySchema,
  threadEventsQuerySchema,
  threadListQuerySchema,
  threadTimelineQuerySchema,
  timelineToolDetailsQuerySchema,
  systemVoiceTranscriptionResponseSchema,
  systemModelsQuerySchema,
  systemProvidersQuerySchema,
  threadTimelineResponseSchema,
  timelineToolDetailsRequestSchema,
  timelineToolDetailsResponseSchema,
  updateEnvironmentRequestSchema,
  updateAutomationRequestSchema,
  updateAutomationConfigRequestSchema,
  updateAutomationEnabledRequestSchema,
  updateProjectRequestSchema,
  updateProjectSourceRequestSchema,
  updateThreadRequestSchema,
  unmanagedWorkspaceSchema,
  managedWorktreeWorkspaceSchema,
  managedCloneWorkspaceSchema,
  workspaceArgsSchema,
  reuseEnvironmentSchema,
  hostEnvironmentSchema,
  sandboxHostEnvironmentSchema,
  SCHEDULE_CRON_MAX_LENGTH,
  SCHEDULE_NAME_MAX_LENGTH,
  SCHEDULE_TIMEZONE_MAX_LENGTH,
  scheduleCronSchema,
  scheduleNameSchema,
  scheduleTimezoneSchema,
  uploadedPromptAttachmentSchema,
  workspaceFileSchema,
} from "./api-types.js";
export type {
  ArchiveThreadRequest,
  Automation,
  AutomationAction,
  AutomationScheduleTrigger,
  AutomationValidation,
  CommitActionResponse,
  CreateAutomationRequest,
  CreateHostJoinRequest,
  CreateHostJoinResponse,
  CreateDraftRequest,
  CreateManagerThreadRequest,
  CreateProjectRequest,
  CreateProjectSourceRequest,
  CreateThreadRequest,
  EnvironmentArgs,
  EnvironmentActionApiError,
  EnvironmentDiffQuery,
  EnvironmentActionFailureDetails,
  EnvironmentActionRequest,
  EnvironmentActionResponse,
  EnvironmentActionType,
  EnvironmentStatusQuery,
  EnvironmentStatusResponse,
  ThreadStorageContentQuery,
  ThreadStorageFilesQuery,
  ProjectAttachmentContentQuery,
  ProjectAttachmentUploadForm,
  ProjectFilesQuery,
  ProjectResponse,
  SendDraftRequest,
  SendDraftResponse,
  SendMessageMode,
  SendMessageRequest,
  ScheduledThreadAutomationAction,
  SquashMergeActionResponse,
  SquashMergeOptions,
  SystemConfigResponse,
  SystemSandboxBackendsResponse,
  SystemSandboxBackendInfo,
  SystemModelsQuery,
  SystemProviderInfo,
  SystemProvidersQuery,
  SystemVoiceTranscriptionForm,
  ThreadContextWindowUsage,
  ThreadDraftListResponse,
  ThreadEventWaitQuery,
  ThreadEventsQuery,
  ThreadListQuery,
  ThreadTimelineQuery,
  TimelineToolDetailsQuery,
  SystemVoiceTranscriptionResponse,
  ThreadTimelineResponse,
  TimelineToolDetailsRequest,
  TimelineToolDetailsResponse,
  UpdateEnvironmentRequest,
  UpdateAutomationRequest,
  UpdateAutomationConfigRequest,
  UpdateAutomationEnabledRequest,
  UpdateProjectRequest,
  UpdateProjectSourceRequest,
  UpdateThreadRequest,
  UploadedPromptAttachment,
  WorkspaceArgs,
  WorkspaceFile,
  WorkspaceFileListResponse,
} from "./api-types.js";

export { createApiClient, createPublicApiClient } from "./public-api.js";
export { typedRoutes } from "@bb/hono-typed-routes";
export type {
  ApiClient,
  PublicApiRoutes,
  PublicApiSchema,
} from "./public-api.js";

export {
  ENVIRONMENT_CHANGE_KINDS,
  HOST_CHANGE_KINDS,
  PROJECT_CHANGE_KINDS,
  REALTIME_ENTITIES,
  SYSTEM_CHANGE_KINDS,
  THREAD_CHANGE_KINDS,
} from "@bb/domain";
export type {
  ChangedMessage,
  ClientMessage,
  EnvironmentChangeKind,
  EnvironmentChangedMessage,
  HostChangeKind,
  HostChangedMessage,
  ProjectChangeKind,
  RealtimeEntity,
  ServerMessage,
  SubscribeMessage,
  SystemChangeKind,
  ThreadChangeKind,
  UnsubscribeMessage,
} from "@bb/domain";
