export type {
  EmptyInput,
  Endpoint,
  PathId,
  PathProjectId,
  PathThreadAndDraft,
  Untyped,
} from "./common.js";

export { apiErrorSchema, domainErrorCodeSchema } from "./errors.js";
export type { ApiError, DomainErrorCode } from "./errors.js";

export {
  commitActionResponseSchema,
  commitOptionsSchema,
  createDraftRequestSchema,
  createProjectRequestSchema,
  createProjectSourceRequestSchema,
  createThreadRequestSchema,
  environmentArgsSchema,
  environmentActionApiErrorSchema,
  environmentActionFailureDetailsSchema,
  environmentActionRequestSchema,
  environmentActionResponseSchema,
  environmentActionTypeSchema,
  environmentStatusResponseSchema,
  projectFileSuggestionSchema,
  projectResponseSchema,
  sendDraftRequestSchema,
  sendDraftResponseSchema,
  sendMessageModeSchema,
  sendMessageRequestSchema,
  squashMergeActionResponseSchema,
  squashMergeOptionsSchema,
  systemConfigResponseSchema,
  systemProviderInfoSchema,
  threadContextWindowUsageSchema,
  systemShutdownAcceptedResponseSchema,
  systemShutdownBlockedResponseSchema,
  systemShutdownBlockingThreadSchema,
  systemShutdownRequestSchema,
  systemVoiceTranscriptionResponseSchema,
  threadTimelineResponseSchema,
  timelineToolDetailsRequestSchema,
  timelineToolDetailsResponseSchema,
  updateProjectRequestSchema,
  updateProjectSourceRequestSchema,
  updateThreadRequestSchema,
  unmanagedWorkspaceSchema,
  managedWorktreeWorkspaceSchema,
  managedCloneWorkspaceSchema,
  workspaceArgsSchema,
  reuseEnvironmentSchema,
  hostEnvironmentSchema,
  sandboxHostEnvironmentSchema,
  uploadedPromptAttachmentSchema,
  workspaceFileSchema,
} from "./api-types.js";
export type {
  CommitActionResponse,
  CommitOptions,
  CreateDraftRequest,
  CreateProjectRequest,
  CreateProjectSourceRequest,
  CreateThreadRequest,
  EnvironmentArgs,
  EnvironmentActionApiError,
  EnvironmentActionFailureDetails,
  EnvironmentActionRequest,
  EnvironmentActionResponse,
  EnvironmentActionType,
  EnvironmentStatusResponse,
  ProjectFileSuggestion,
  ProjectResponse,
  SendDraftRequest,
  SendDraftResponse,
  SendMessageMode,
  SendMessageRequest,
  SquashMergeActionResponse,
  SquashMergeOptions,
  SystemConfigResponse,
  SystemProviderInfo,
  ThreadContextWindowUsage,
  SystemShutdownAcceptedResponse,
  SystemShutdownBlockedResponse,
  SystemShutdownBlockingThread,
  SystemShutdownRequest,
  SystemVoiceTranscriptionResponse,
  ThreadTimelineResponse,
  TimelineToolDetailsRequest,
  TimelineToolDetailsResponse,
  UpdateProjectRequest,
  UpdateProjectSourceRequest,
  UpdateThreadRequest,
  UploadedPromptAttachment,
  WorkspaceArgs,
  WorkspaceFile,
} from "./api-types.js";

export { createApiClient, createPublicApiClient } from "./public-api.js";
export type {
  ApiClient,
  PublicApiRoutes,
  PublicApiSchema,
} from "./public-api.js";

export {
  ENVIRONMENT_CHANGE_KINDS,
  PROJECT_CHANGE_KINDS,
  SYSTEM_CHANGE_KINDS,
  THREAD_CHANGE_KINDS,
} from "@bb/domain";
export type {
  ChangedMessage,
  ClientMessage,
  EnvironmentChangeKind,
  EnvironmentChangedMessage,
  ProjectChangeKind,
  RealtimeEntity,
  ServerMessage,
  SubscribeMessage,
  SystemChangeKind,
  ThreadChangeKind,
  UnsubscribeMessage,
} from "@bb/domain";
